import { buildProgram, parseMealRows } from './source-parser.mjs';

const DAY_NAMES=['SUNDAY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY'];
const WORK_DAYS=['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY'];
const KEY='project-bane.data.v5';
const defaults={view:'dashboard',program:null,nutrition:[],sessions:{},weights:[],sources:{},settings:{programStart:'',goalWeight:250,activeBlock:'Block 1'}};
let state=load();
let selectedDay=null;

function load(){try{return deepMerge(defaults,JSON.parse(localStorage.getItem(KEY)||'{}'));}catch{return structuredClone(defaults);}}
function deepMerge(base,value){return {...base,...value,settings:{...base.settings,...(value?.settings||{})}};}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function todayDay(){return DAY_NAMES[new Date().getDay()];}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function programDay(d){return state.program?.days?.[d];}
function conditionDay(d){return state.program?.conditioning?.[d];}
function weekFor(date=localDate()){
  if(!state.settings.programStart)return 1;
  const start=new Date(`${state.settings.programStart}T00:00:00`), target=new Date(`${date}T00:00:00`);
  const diff=Math.floor((target-start)/86400000);
  return Math.max(1,Math.floor(diff/7)+1);
}
function sessionKey(d,date=localDate(),block=state.settings.activeBlock){return `${date}|${block}|W${weekFor(date)}|${d}`;}
function getSession(d=todayDay(),date=localDate()){return state.sessions[sessionKey(d,date)]||{completed:false,actuals:{},notes:'',focus:programDay(d)?.focus||''};}
function totals(date=localDate()){return state.nutrition.filter(x=>x.date===date).reduce((a,x)=>{const carbs=Number(x.carbs)||0,fiber=Number(x.fiber)||0;return {cal:a.cal+(Number(x.calories)||0),protein:a.protein+(Number(x.protein)||0),net:a.net+(x.netCarbs!=null?Number(x.netCarbs):carbs-fiber)}},{cal:0,protein:0,net:0});}
function setView(v){state.view=v;save();render();}

function nav(){return `<aside class="sidebar"><div class="brand"><div class="mark">B</div><div><b>PROJECT BANE</b><span>52-WEEK TRANSFORMATION</span></div></div><nav>${[['dashboard','Today'],['today','Workout'],['nutrition','Food'],['progress','Progress'],['history','History'],['sources','Sources'],['settings','Settings']].map(([v,label])=>`<button class="nav ${state.view===v?'active':''}" data-view="${v}">${label}</button>`).join('')}</nav><div class="sync"><i></i>Local data active</div></aside>`;}
function shell(content,title=state.view==='dashboard'?'Today':state.view==='today'?'Workout':state.view[0].toUpperCase()+state.view.slice(1)){return `${nav()}<main><header><div><div class="eyebrow">${new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'}).format(new Date()).toUpperCase()}</div><h1>${title}</h1></div><button class="primary" id="printTop">Print Today's Workout</button></header>${content}</main>`;}
function dashboard(){const d=todayDay(),x=programDay(d),c=conditionDay(d),n=totals(),latest=state.weights.at(-1),s=getSession(d);return shell(`<div class="grid four"><div class="card"><div class="label">CURRENT BLOCK</div><div class="big">${esc(state.settings.activeBlock)}</div><div class="muted">Week ${weekFor()} of 52</div></div><div class="card"><div class="label">TODAY</div><div class="big">${d}</div><div class="muted">${esc(x?.focus||'Recovery / Weekly Review')}</div></div><div class="card"><div class="label">WEIGHT</div><div class="big">${latest?.weight??'—'} <small>lb</small></div><div class="muted">${latest?.date||'No weigh-in recorded'}</div></div><div class="card"><div class="label">TODAY'S NUTRITION</div><div class="big">${Math.round(n.cal)} <small>cal</small></div><div class="muted">${Math.round(n.protein)}g protein · ${Math.round(n.net)}g net carbs</div></div></div><section class="card today-card"><div><div class="label">TODAY'S PLAN</div><h2>${esc(x?.focus||'RECOVERY / WEEKLY REVIEW')}</h2><p class="muted">${x?.exercises?.length?'Print the sheet, train away from the app, then record actuals if you want.':'Recovery day. Review the week and prepare for the next session.'}</p>${c?`<p class="muted">Conditioning: ${esc(c.cardio)}</p>`:''}</div><div class="actions"><button class="primary" data-view="today">Open Workout</button><button class="ghost" id="printDash">Print Sheet</button></div></section><section class="card"><div class="label">WEEK AT A GLANCE</div><div class="days">${WORK_DAYS.map(dy=>{const z=programDay(dy),done=state.sessions[sessionKey(dy)]?.completed;return `<button class="day ${dy===d?'today':''} ${done?'done':''}" data-day="${dy}"><b>${dy.slice(0,3)}</b><small>${esc(z?.focus||'Recovery')}</small>${done?'<em>DONE</em>':''}</button>`}).join('')}</div></section><section class="grid three"><div class="card"><div class="label">TRAINING</div><div class="stat"><b>${s.completed?'1':'0'}</b><span>session today</span></div><div class="stat"><b>${Object.keys(state.sessions).length}</b><span>logged sessions</span></div></div><div class="card"><div class="label">CONDITIONING</div><h3>${esc(c?.cardio||'Recovery')}</h3><p class="muted">${esc(c?.intent||'')}</p></div><div class="card"><div class="label">CORE</div><h3>${esc(c?.emphasis||'—')}</h3><p class="pre">${esc(c?.core||'—')}</p></div></section>`;}
function workout(d=selectedDay||todayDay()){const x=programDay(d),c=conditionDay(d),s=getSession(d);if(!x?.exercises?.length)return shell(`<section class="card hero"><div><div class="label">${esc(state.settings.activeBlock)} · WEEK ${weekFor()} · ${d}</div><h2>${esc(x?.focus||'RECOVERY / WEEKLY REVIEW')}</h2><p class="muted">No strength workout is programmed for this day.</p></div><div class="actions"><button class="ghost" data-view="dashboard">Back</button><button class="primary" id="printToday">Print Today's Sheet</button></div></section><section class="card"><h3>Conditioning + Core</h3><p><b>Cardio:</b> ${esc(c?.cardio||'—')}</p><p><b>Core:</b> ${esc(c?.emphasis||'—')}</p><p class="pre">${esc(c?.core||'—')}</p></section>`);return shell(`<section class="card hero"><div><div class="label">${esc(state.settings.activeBlock)} · WEEK ${weekFor()} · ${d}</div><h2>${esc(x.focus)}</h2><p class="muted">Prescription is the source of truth. Actual performance is optional.</p></div><div class="actions"><button class="ghost" data-view="dashboard">Back</button><button class="primary" id="printToday">Print Today's Sheet</button><button class="ghost" id="complete">${s.completed?'Completed ✓':'Mark Complete'}</button></div></section><section class="card"><h3>Warm-up & Mobility</h3>${(state.program.warmup||[]).map(v=>`<div class="checkline">□ ${esc(v)}</div>`).join('')}</section><section class="card"><div class="section-title"><h3>Strength</h3><span class="muted">Actual performance</span></div>${x.exercises.map((e,i)=>exercise(e,i,s.actuals?.[i])).join('')}</section><section class="card"><h3>Conditioning + Core</h3><p><b>Cardio:</b> ${esc(c?.cardio||'—')}</p><p><b>Core emphasis:</b> ${esc(c?.emphasis||'—')}</p><p class="pre">${esc(c?.core||'—')}</p><p class="muted">${esc(c?.notes||'')}</p></section><section class="card"><h3>Workout Notes</h3><textarea id="notes" placeholder="Optional notes...">${esc(s.notes)}</textarea></section>`,`${d[0]+d.slice(1).toLowerCase()} Workout`);}
function exercise(e,i,a){const n=Math.max(1,Math.min(6,parseInt(String(e.sets).match(/\d+/)?.[0]||3)));return `<div class="exercise"><b>${i+1}. ${esc(e.exercise)}</b><div class="muted">${esc(e.section)} · ${esc(e.sets)} sets · ${esc(e.reps)} reps</div><div class="setgrid">${Array.from({length:n},(_,j)=>{const q=a?.[j]||{};return `<div><label>Set ${j+1}</label><input data-actual="${i}:${j}:weight" value="${esc(q.weight)}" placeholder="lb"><input data-actual="${i}:${j}:reps" value="${esc(q.reps)}" placeholder="reps"><input data-actual="${i}:${j}:note" value="${esc(q.note)}" placeholder="note"></div>`}).join('')}</div></div>`;}
function nutrition(){const n=totals();return shell(`<section class="grid four"><div class="card"><div class="label">CALORIES TODAY</div><div class="big">${Math.round(n.cal)}</div></div><div class="card"><div class="label">PROTEIN</div><div class="big">${Math.round(n.protein)}g</div></div><div class="card"><div class="label">NET CARBS</div><div class="big">${Math.round(n.net)}g</div></div><div class="card"><div class="label">ENTRIES</div><div class="big">${state.nutrition.filter(x=>x.date===localDate()).length}</div></div></section><section class="card"><h2>Meal Log</h2><table><thead><tr><th>Date</th><th>Meal</th><th>Food</th><th>Serving</th><th>Calories</th><th>Protein</th><th>Net Carbs</th></tr></thead><tbody>${state.nutrition.slice().reverse().map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.meal)}</td><td>${esc(x.food)}</td><td>${esc(x.quantity)}</td><td>${x.calories??'—'}</td><td>${x.protein??'—'}g</td><td>${x.netCarbs??'—'}g</td></tr>`).join('')||'<tr><td colspan="7">No meal entries.</td></tr>'}</tbody></table></section>`);}
function progress(){const w=state.weights,latest=w.at(-1)?.weight,goal=Number(state.settings.goalWeight)||250;return shell(`<section class="grid four"><div class="card"><div class="label">CURRENT WEIGHT</div><div class="big">${latest??'—'} <small>lb</small></div></div><div class="card"><div class="label">GOAL</div><div class="big">${goal} <small>lb</small></div></div><div class="card"><div class="label">REMAINING</div><div class="big">${latest==null?'—':Math.max(0,latest-goal).toFixed(1)} <small>lb</small></div></div><div class="card"><div class="label">WEIGH-INS</div><div class="big">${w.length}</div></div></section><section class="card"><div class="section-title"><h2>Weight History</h2><div class="actions"><input id="weightInput" type="number" step=".1" placeholder="lb"><button class="primary" id="recordWeight">Record</button></div></div><table><thead><tr><th>Date</th><th>Weight</th><th>Change</th></tr></thead><tbody>${w.slice().reverse().map((x,i,a)=>`<tr><td>${esc(x.date)}</td><td>${x.weight} lb</td><td>${i<a.length-1?`${x.weight-a[i+1].weight>0?'+':''}${(x.weight-a[i+1].weight).toFixed(1)} lb`:'—'}</td></tr>`).join('')||'<tr><td colspan="3">No weigh-ins recorded.</td></tr>'}</tbody></table></section>`);}
function history(){const rows=Object.entries(state.sessions).sort((a,b)=>b[0].localeCompare(a[0]));return shell(`<section class="card"><h2>Workout History</h2><p class="muted">Historical actuals remain separate from the active prescription.</p>${rows.map(([k,s])=>`<div class="history-row"><div><b>${esc(k.split('|')[3]||'Workout')}</b><div class="muted">${esc(k.split('|')[0])} · ${esc(k.split('|')[1])} · ${esc(k.split('|')[2])}</div></div><span class="pill">${s.completed?'COMPLETED':'LOGGED'}</span></div>`).join('')||'<p class="muted">No workout history yet.</p>'}</section>`);}
function sources(){return shell(`<section class="grid two"><div class="card"><h2>Canonical Sources</h2><p class="muted">The source documents control the prescription. Importing a new source never deletes training history.</p>${[['program','Workout Program'],['nutrition','Meal Log'],['handoff','Workout System Handoff']].map(([k,n])=>`<div class="source-row"><div><b>${n}</b><div class="muted">${esc(state.sources[k]?.name||'Bundled GitHub source')}</div></div><span class="pill">${state.sources[k]?'UPDATED':'BUNDLED'}</span></div>`).join('')}</div><div class="card"><h2>Update Sources</h2><p class="muted">Choose a canonical workbook or Markdown handoff. Bane will inspect it before applying changes.</p><button class="primary" id="chooseSource">Choose Source</button><input id="sourceFile" type="file" accept=".xlsx,.xls,.md,.markdown" hidden><div id="sourcePreview"></div></div></section>`);}
function settings(){return shell(`<section class="grid two"><div class="card"><h2>Program Calendar</h2><p class="muted">Set the first day of the active block. Bane calculates the training week from this date.</p><label>Program Start Date</label><input id="programStart" type="date" value="${esc(state.settings.programStart)}"><label>Active Block</label><input id="activeBlock" value="${esc(state.settings.activeBlock)}"><button class="primary" id="saveProgramSettings">Save</button></div><div class="card"><h2>Progress Target</h2><label>Goal Weight</label><input id="goalWeight" type="number" step=".1" value="${state.settings.goalWeight}"><button class="primary" id="saveGoal">Save Goal</button><hr><h3>Data Backup</h3><p class="muted">Export your local Bane data before changing computers or clearing browser data.</p><button class="ghost" id="exportBackup">Export Backup</button><input id="backupFile" type="file" accept=".json" hidden><button class="ghost" id="importBackup">Restore Backup</button></div></section>`);}
const views={dashboard,today:()=>workout(selectedDay||todayDay()),nutrition,progress,history,sources,settings};
function render(){document.querySelector('#dateLabel').textContent=new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'}).format(new Date()).toUpperCase();document.querySelector('#pageTitle').textContent=state.view==='today'?'Workout':state.view[0].toUpperCase()+state.view.slice(1);document.querySelector('#view').innerHTML=views[state.view]();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));bind();}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{selectedDay=b.dataset.day;state.view='today';render();});document.querySelector('#printTop')?.addEventListener('click',()=>printWorkout(selectedDay||todayDay()));document.querySelector('#printDash')?.addEventListener('click',()=>printWorkout(todayDay()));document.querySelector('#printToday')?.addEventListener('click',()=>printWorkout(selectedDay||todayDay()));document.querySelector('#complete')?.addEventListener('click',()=>{const d=selectedDay||todayDay(),k=sessionKey(d),s=getSession(d);s.completed=!s.completed;s.focus=programDay(d)?.focus||'';state.sessions[k]=s;save();render();});document.querySelector('#notes')?.addEventListener('change',e=>{const d=selectedDay||todayDay(),k=sessionKey(d),s=getSession(d);s.notes=e.target.value;s.focus=programDay(d)?.focus||'';state.sessions[k]=s;save();});document.querySelectorAll('[data-actual]').forEach(i=>i.addEventListener('change',()=>{const [ei,si,f]=i.dataset.actual.split(':'),d=selectedDay||todayDay(),k=sessionKey(d),s=getSession(d);s.actuals[ei]=s.actuals[ei]||{};s.actuals[ei][si]=s.actuals[ei][si]||{};s.actuals[ei][si][f]=i.value;s.focus=programDay(d)?.focus||'';state.sessions[k]=s;save();}));document.querySelector('#recordWeight')?.addEventListener('click',()=>{const v=Number(document.querySelector('#weightInput').value);if(v){state.weights.push({date:localDate(),weight:v});state.weights.sort((a,b)=>a.date.localeCompare(b.date));save();render();}});document.querySelector('#chooseSource')?.addEventListener('click',()=>document.querySelector('#sourceFile').click());document.querySelector('#sourceFile')?.addEventListener('change',e=>stageSource(e.target.files[0]));document.querySelector('#saveProgramSettings')?.addEventListener('click',()=>{state.settings.programStart=document.querySelector('#programStart').value;state.settings.activeBlock=document.querySelector('#activeBlock').value.trim()||'Block 1';save();render();});document.querySelector('#saveGoal')?.addEventListener('click',()=>{state.settings.goalWeight=Number(document.querySelector('#goalWeight').value)||250;save();render();});document.querySelector('#exportBackup')?.addEventListener('click',exportBackup);document.querySelector('#importBackup')?.addEventListener('click',()=>document.querySelector('#backupFile').click());document.querySelector('#backupFile')?.addEventListener('change',e=>importBackup(e.target.files[0]));}
async function stageSource(file){if(!file)return;const box=document.querySelector('#sourcePreview');try{if(/\.md$/i.test(file.name)){const text=await file.text();box.innerHTML=`<div class="source-preview"><b>${esc(file.name)}</b><p>${text.length.toLocaleString()} characters detected.</p><button class="primary" id="acceptSource">Accept Handoff</button></div>`;document.querySelector('#acceptSource').onclick=()=>{state.sources.handoff={name:file.name,importedAt:new Date().toISOString()};save();box.innerHTML='<p class="muted">Handoff accepted.</p>';};return;}const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});const names=wb.SheetNames;const rows=name=>name&&wb.Sheets[name]?XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:''}):[];const summaryName=names.find(n=>n.toUpperCase()==='BLOCK 1 PROGRAM'||/^BLOCK\s*\d+\s*PROGRAM$/i.test(n));const condName=names.find(n=>/CONDITIONING/i.test(n));const dayRows={};for(const d of WORK_DAYS){const n=names.find(x=>x.toUpperCase()===d);if(n)dayRows[d]=rows(n);}if(summaryName||condName||Object.keys(dayRows).length){const parsed=buildProgram(summaryName?rows(summaryName):[],dayRows,condName?rows(condName):[],{block:(file.name.match(/BLOCK\s*\d+/i)?.[0]||state.settings.activeBlock),weeks:'Weeks 1–4'});const dayCount=Object.keys(parsed.days||{}).length,condCount=Object.keys(parsed.conditioning||{}).length;box.innerHTML=`<div class="source-preview"><b>${esc(file.name)}</b><p>Detected ${names.length} sheets · ${dayCount} training days · ${condCount} conditioning entries.</p><p class="muted">This is a preview. Nothing has changed yet.</p><button class="primary" id="acceptSource">Apply Program</button></div>`;document.querySelector('#acceptSource').onclick=()=>{state.program=parsed;state.settings.activeBlock=parsed.block||state.settings.activeBlock;state.sources.program={name:file.name,importedAt:new Date().toISOString(),sheets:names};save();box.innerHTML='<p class="muted">Program source applied. Historical sessions were preserved.</p>';render();};return;}const mealName=names.find(n=>/daily\s*log/i.test(n)||/meal/i.test(n));if(mealName){const parsed=parseMealRows(rows(mealName));box.innerHTML=`<div class="source-preview"><b>${esc(file.name)}</b><p>Detected ${parsed.length} meal entries.</p><p class="muted">Existing meal history will be replaced only after approval; workout history is untouched.</p><button class="primary" id="acceptSource">Apply Meal Log</button></div>`;document.querySelector('#acceptSource').onclick=()=>{state.nutrition=parsed;state.sources.nutrition={name:file.name,importedAt:new Date().toISOString(),sheets:names};save();box.innerHTML='<p class="muted">Meal log applied.</p>';render();};return;}box.innerHTML='<p>Could not identify a supported canonical Bane workbook structure.</p>';}catch(err){box.innerHTML=`<p>Import error: ${esc(err.message)}</p>`;}}
function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`project-bane-backup-${localDate()}.json`;a.click();URL.revokeObjectURL(url);}
async function importBackup(file){if(!file)return;try{const incoming=JSON.parse(await file.text());if(!incoming||typeof incoming!=='object')throw Error('Invalid backup');state=deepMerge(defaults,incoming);save();render();}catch(err){alert(`Could not restore backup: ${err.message}`);}}
function printWorkout(d){const x=programDay(d),c=conditionDay(d);if(!x)return;const n=state.program?.warmup||[];let html=`<!doctype html><html><head><title>Project Bane — ${d}</title><style>body{font:12px Arial,sans-serif;color:#111;margin:22px}h1{font-size:22px;margin-bottom:4px}h2{font-size:15px;border-bottom:2px solid #111;padding:5px 0;margin-top:16px}p{margin:5px 0}.pre{white-space:pre-wrap}.warm{line-height:1.7}table{width:100%;border-collapse:collapse;margin:5px 0 12px;table-layout:fixed}th,td{border:1px solid #777;padding:5px;height:24px}th{font-size:11px}th:nth-child(1),td:nth-child(1){width:8%}th:nth-child(2),td:nth-child(2){width:16%}th:nth-child(3),td:nth-child(3){width:14%}th:nth-child(4),td:nth-child(4){width:auto}.notes{height:70px}@media print{body{margin:12mm}}</style></head><body><h1>PROJECT BANE — ${esc(d)}</h1><p>${esc(state.settings.activeBlock)} · Week ${weekFor()} · ${new Intl.DateTimeFormat('en-US').format(new Date())}</p><h2>WARM-UP & MOBILITY</h2><div class="warm">${n.map(v=>`□ ${esc(v)}`).join('<br>')}</div><h2>${esc(x.focus)}</h2>`;for(const e of x.exercises){const sets=Math.max(1,Math.min(6,parseInt(String(e.sets).match(/\d+/)?.[0]||3)));html+=`<b>${esc(e.exercise)}</b> — ${esc(e.section)} · ${esc(e.sets)} × ${esc(e.reps)}<table><tr><th>Set</th><th>Weight</th><th>Reps</th><th>Notes</th></tr>${Array.from({length:sets},(_,i)=>`<tr><td>${i+1}</td><td></td><td></td><td></td></tr>`).join('')}</table>`;}html+=`<h2>CONDITIONING + CORE</h2><p><b>Cardio:</b> ${esc(c?.cardio||'—')}</p><p><b>Core emphasis:</b> ${esc(c?.emphasis||'—')}</p><p class="pre">${esc(c?.core||'—')}</p><h2>WORKOUT NOTES</h2><table><tr><td class="notes"></td></tr><tr><td class="notes"></td></tr></table></body></html>`;const w=window.open('','_blank');if(!w){alert('Allow pop-ups for Project Bane to print the workout.');return;}w.document.write(html);w.document.close();w.focus();setTimeout(()=>w.print(),150);}
async function boot(){try{if(!state.program){state.program=await fetch('./data/program.json?'+Date.now()).then(r=>r.json());save();}if(!state.nutrition?.length){const data=await fetch('./data/nutrition.json?'+Date.now()).then(r=>r.json());if(Array.isArray(data)&&data.length)state.nutrition=data;save();}}catch(err){console.error('Bane source load:',err);}render();}
boot();
