const text = v => String(v ?? '').trim();
const number = v => { if (v === null || v === undefined || String(v).trim() === '') return null; const n = Number(v); return Number.isFinite(n) ? n : null; };
const dateValue = v => { if (v instanceof Date && !Number.isNaN(v.getTime())) return v.toISOString().slice(0,10); const s=text(v); if(!s)return ''; const d=new Date(s); return Number.isNaN(d.getTime())?s:d.toISOString().slice(0,10); };
const splitExercise = value => text(value).split(/\n+/).map(x=>x.trim()).filter(Boolean).map(line=>{const m=line.match(/^(.*?)\s+[—-]\s+(\d+(?:\.\d+)?(?:-\d+)?|Hard sets|Rounds)\s*[×x]\s*(.+)$/i); if(!m)return {exercise:line,sets:null,reps:''}; return {exercise:m[1].trim(),sets:m[2].includes('-')?m[2]:number(m[2]),reps:m[3].trim()};});
export function parseWorkoutRows(rows){if(!Array.isArray(rows)||!rows.length)return [];const header=rows[0].map(text),idx=n=>header.findIndex(h=>h.toLowerCase()===n.toLowerCase()),section=idx('Section'),exercise=idx('Exercise'),sets=idx('Sets'),reps=idx('Rep Range');if(exercise<0)return [];return rows.slice(1).filter(r=>text(r[exercise])).map(r=>({section:text(r[section]),exercise:text(r[exercise]),sets:number(r[sets]),reps:text(r[reps])}));}
export function parseWorkoutSummaryRows(rows){if(!Array.isArray(rows)||rows.length<5)return [];const header=rows[3].map(text),dayIdx=header.findIndex(h=>h.toUpperCase()==='DAY'),focusIdx=header.findIndex(h=>h.toUpperCase()==='FOCUS');if(dayIdx<0)return [];const columns=['PRIMARY','SUPERSET 1','SUPERSET 2','SUPERSET 3','FINISHERS'];return rows.slice(4).filter(r=>text(r[dayIdx])).map(r=>({day:text(r[dayIdx]).toUpperCase(),focus:text(r[focusIdx]),exercises:columns.flatMap(section=>{const i=header.findIndex(h=>h.toUpperCase()===section);return i<0?[]:splitExercise(r[i]).map(e=>({...e,section}));})}));}
export function parseConditioningRows(rows){if(!Array.isArray(rows)||rows.length<5)return [];const header=rows[3].map(text),idx=n=>header.findIndex(h=>h.toLowerCase()===n.toLowerCase()),day=idx('DAY'),cardio=idx('CARDIO / CONDITIONING'),emphasis=idx('CORE EMPHASIS'),core=idx('CORE WORKOUT'),intent=idx('INTENT'),notes=idx('NOTES / TRACKING');if(day<0)return [];return rows.slice(4).filter(r=>text(r[day])).map(r=>({day:text(r[day]).toUpperCase(),cardio:text(r[cardio]),emphasis:text(r[emphasis]),core:text(r[core]),intent:text(r[intent]),notes:text(r[notes])}));}
export function parseMealRows(rows){if(!Array.isArray(rows)||!rows.length)return [];const header=rows[0].map(text),idx=n=>header.findIndex(h=>h.toLowerCase()===n.toLowerCase()),date=idx('Date'),meal=idx('Meal'),food=idx('Food / Drink'),quantity=idx('Quantity / Serving'),calories=idx('Calories'),protein=idx('Protein (g)'),carbs=idx('Total Carbs (g)'),fiber=idx('Fiber (g)'),net=idx('Net Carbs (g)'),notes=idx('Notes');if(date<0||food<0)return [];return rows.slice(1).filter(r=>text(r[date])&&text(r[food])).map(r=>{const c=number(r[carbs]),f=number(r[fiber]),n=number(r[net]);return {date:dateValue(r[date]),meal:text(r[meal]),food:text(r[food]),quantity:text(r[quantity]),calories:number(r[calories]),protein:number(r[protein]),carbs:c,fiber:f,netCarbs:n??(c!=null&&f!=null?c-f:null),notes:text(r[notes])};});}
export function buildProgram(summaryRows,dayRows,conditioningRows,meta={}){const summary=parseWorkoutSummaryRows(summaryRows),dayMap=Object.fromEntries(summary.map(x=>[x.day,x]));for(const [day,rows] of Object.entries(dayRows||{})){const exercises=parseWorkoutRows(rows);if(exercises.length)dayMap[day.toUpperCase()]={...(dayMap[day.toUpperCase()]||{day:day.toUpperCase(),focus:''}),exercises};}return {block:meta.block||'Block 1',weeks:meta.weeks||'Weeks 1–4',warmup:meta.warmup||[],days:dayMap,conditioning:Object.fromEntries(parseConditioningRows(conditioningRows).map(x=>[x.day,x]))};}
